language: node_js

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: coverage
      node_js: "13"
      os:
        - linux
      script:
        - npm t
        - npm run coverage
